import Head from 'next/head';
import { Poppins } from 'next/font/google';
import NavBar from '@/components/NavBar/NavBar';
import { useState } from 'react';
import Hero from '@/components/Hero/Hero';
import SideDrawer from '@/components/SideDrawer/SideDrawer';
import About from '@/components/About/About';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['200', '300', '400', '500', '600', '700'],
  style: 'normal',
});

export default function Home() {
  const [isSideDrawerActive, setIsSideDrawerActive] = useState(false);

  return (
    <>
      <Head>
        <title>Ali Haghayegh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" sizes="32x32" type="image/png" href="/icon.png" />
      </Head>
      <div className={`${poppins.variable} font-sans text-nuetral-dark `}>
        <NavBar
          isSideDrawerActive={isSideDrawerActive}
          setIsSideDrawerActive={setIsSideDrawerActive}
        />
        <main
          className={`max-w-screen-2xl  mx-auto px-6 sm:px-10 md:px-16 lg:px-32`}
        >
          <Hero />
          <About />
        </main>
        <SideDrawer
          isSideDrawerActive={isSideDrawerActive}
          setIsSideDrawerActive={setIsSideDrawerActive}
        />
      </div>
    </>
  );
}
